#.github/workflows/sync.yml
name: Sync Fork

on: 
 
   schedule: 
   - cron: '0 0 18 * * ' # 
jobs: 
  repo-sync: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: TG908/fork-sync@v1.6.3
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}  
            owner: gcqi1976 # fork gcqi1976 user 
            head: main # fork https://wget.la/https://raw.githubusercontent.com/gcqi1976/xt/main/others_output.txt branch 
            base: main # https://raw.githubusercontent.com/gcqi1976/gao/refs/heads/master/list.txt branch

